project:
  type: website

website:
  title: "Visual Project G1"
  favicon: images/logo1.png
  navbar:
    left:
      - text: "Proposal"
        href: "Proposal/proposal.html"

      - text: "Poster"
        href: "Poster/poster.html"
     
      - text: "Meeting Minutes"
        href: "Meeting_Minutes/meeting_minutes.html"  

      - text: "Shiny App"
        href: "https://quynhtrangdo.shinyapps.io/behind_the_reef/" 
      
      - text: "User Guide"
        href: "user_guide/user_guide.html"
      
      - text: "Github"
        href:   "" 

    

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

