project:
  type: website

website:
  title: "Visual Project G1"
  favicon: images/logo1.png
  navbar:
    left:
      - text: "Proposal"
        href: "Proposal/proposal.html"

      - text: "Methodology"
        href: ""
     
      - text: "Findings"
        href:  ""
      
      - text: "Poster"
        href: ""
     
      - text: "Meeting Minutes"
        href: "Meeting_Minutes/meeting_minutes.html"  


    right:
    
      - text: "The Team"
      - href:   ""  
      
      - text: "Shiny App"
      - href:   "" 
      - text: "Github"
      - href:   "" 

    

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

